name: Update Latest Tag

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check if release tag is not 'latest'
      run: |
        if [[ "${{ github.event.release.tag_name }}" != 'latest' ]]; then
          echo "Release tag is not 'latest'."
        else
          echo "Release tag is 'latest'. Exiting workflow."
          exit 78
        fi

    - name: Remove existing 'latest' tag
      run: |
        git tag -d latest || true
        git push origin :refs/tags/latest || true

    - name: Create new 'latest' tag
      run: |
        git tag latest
        git push origin latest
