name: Update Latest Release
env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Set the GH_TOKEN environment variable
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-latest-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Remove "latest" release
        run: |
          latest_release_id=$(gh GH_TOKEN release list | grep "latest" | awk '{print $1}')
          if [ -n "$latest_release_id" ]; then
            gh GH_TOKEN release delete $latest_release_id --yes
          fi

      - name: Create new "latest" release
        run: |
          gh GH_TOKEN release create latest ./* --notes "Release notes for latest version" --repo ${{ github.repository }}
