name: Update Latest Release
on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  update-latest-release:
    runs-on: ubuntu-latest
    if: github.event.release.tag_name != 'latest'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Remove "latest" release
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Set the GH_TOKEN environment variable
        run: |
          latest_release_id=$(gh release list | grep "latest" | awk '{print $1}')
          if [ -n "$latest_release_id" ]; then
            gh release delete $latest_release_id --yes
          fi

      - name: Create new "latest" release
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Set the GH_TOKEN environment variable
      
        run: |
          gh release create latest --notes "Release notes for latest version" --target $(git rev-parse HEAD)
