name: Update Latest Tag

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    if: github.event.release.tag_name != 'latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Remove "latest" tag
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Set the GH_TOKEN environment variable
        run: |
          latest_tag_id=$(gh tag list | grep "latest" | awk '{print $1}')
          if [ -n "$latest_tag_id" ]; then
            gh tag delete $latest_tag_id --yes
          fi

      - name: Create new "latest" tag
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Set the GH_TOKEN environment variable

        run: |
          gh repo create-tag <tag_name> <commit_sha> -m "Tag description"

