name: Update Latest Release
on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  update-latest-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Remove "latest" release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git rev-parse refs/tags/latest >/dev/null 2>&1; then
            git tag -d latest
            git push origin :refs/tags/latest
          else
            echo "Tag 'latest' does not exist, skipping deletion."
          fi

      - name: Create new "latest" release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --local http.extraHeader "Authorization: Bearer ${GITHUB_TOKEN}"
          git tag latest
          git push origin latest
